mode: pre_cg_complex

complex_gro: BsADH_NAD.gro

protein:
  molname: Active
  reference_pdb: BsADH_reference.pdb
  anchor_groups: ["A 8 10 11", "D 8 10 11"]

cofactor:
  molname: NAD
  itp: NAD.itp
  count: 4

topology:
  protein_itp: BsADH_NAD.itp
  include_go: true
  go_files_glob: "go_*"
