[theme]
base = "dark"
primaryColor = "#20C7C9"
backgroundColor = "#08131F"
secondaryBackgroundColor = "#0E2133"
textColor = "#F5F8FA"
font = "sans serif"

[server]
maxUploadSize = 300

[browser]
gatherUsageStats = false
