[theme]
base = "dark"
primaryColor = "#35C9D3"
backgroundColor = "#07131C"
secondaryBackgroundColor = "#0C202C"
textColor = "#F3F7FA"
font = "sans serif"

[server]
maxUploadSize = 300

[browser]
gatherUsageStats = false
